---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---

Install the packages needed for the project
```{r Package Install, message=FALSE}
#install.packages("tidyverse")
```

Initialize the libraries needed to make the code run
```{r Library Declares, message=FALSE}
library("tidyverse")
library("tidyr")
library("dplyr")
library("readr")
library("ggplot2")
```

```{r message=FALSE}
survey <- read_csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/music-survey.csv")
preferences <- read_csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/preferences-survey.csv")
```

Renaming Survey Column Names
```{r}
colnames(survey)[3] <- "pseudonym"
colnames(survey)[2] <- "pseudonym_generator"
colnames(survey)[6] <- "academic_year"
colnames(survey)[7] <- "year_born"
colnames(survey)[1] <- "time_submitted"
colnames(survey)[4] <- "sex"
colnames(survey)[5] <- "academic_major"
colnames(survey)[8] <- "instrument_list"
colnames(survey)[9] <- "favorite_song_artist"
colnames(survey)[10] <- "favorite_song"
colnames(survey)[11] <- "favorite_song_link"

colnames(preferences)[2] <- "pseudonym"
```

Lets create a table for person and favorite song

Standardizing the time format in both the preferences and survey tables

```{r}
survey$time_submitted <- as.POSIXlt( survey$time_submitted, na = character(), format = "%m/%d/%y %H:%M", locale = default_locale() )

preferences$Timestamp <- as.POSIXlt( preferences$Timestamp, na = character(), format = "%m/%d/%y %H:%M", locale = default_locale() )
```
```{r}
view(survey)
#aes(x, y): x = x-axis, y = y-axis
#f <- ggplot(mpg, aes(cty, hwy))
  #plot name <- ggplot(data set, x/y axes)
```

Ratings Tibble Cleaning
```{r}
#(colnames(Ratings)[3]<-"favorite_song_link"
```

GGPlot Testing
```{r}
GP <- ggplot(survey, aes(pseudonym, year_born))
```



